# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'propertieswindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PropertiesWindow(object):
    def setupUi(self, PropertiesWindow):
        PropertiesWindow.setObjectName("PropertiesWindow")
        PropertiesWindow.resize(363, 207)
        self.centralwidget = QtWidgets.QWidget(PropertiesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 362, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dataset_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dataset_label.setObjectName("dataset_label")
        self.verticalLayout_3.addWidget(self.dataset_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tl_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tl_enabled.setEnabled(True)
        self.tl_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tl_enabled.setCheckable(True)
        self.tl_enabled.setObjectName("tl_enabled")
        self.gridLayout.addWidget(self.tl_enabled, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tr_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tr_enabled.setCheckable(True)
        self.tr_enabled.setObjectName("tr_enabled")
        self.gridLayout.addWidget(self.tr_enabled, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tl_label.setObjectName("tl_label")
        self.gridLayout.addWidget(self.tl_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.three_d_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.three_d_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.three_d_enabled.setCheckable(True)
        self.three_d_enabled.setObjectName("three_d_enabled")
        self.gridLayout.addWidget(self.three_d_enabled, 3, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bl_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bl_enabled.setCheckable(True)
        self.bl_enabled.setObjectName("bl_enabled")
        self.gridLayout.addWidget(self.bl_enabled, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_combo_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tl_combo_b.setObjectName("tl_combo_b")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.gridLayout.addWidget(self.tl_combo_b, 0, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_combo_a = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.bl_combo_a.setObjectName("bl_combo_a")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.gridLayout.addWidget(self.bl_combo_a, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tr_label.setObjectName("tr_label")
        self.gridLayout.addWidget(self.tr_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bl_label.setObjectName("bl_label")
        self.gridLayout.addWidget(self.bl_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.three_d_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.three_d_label.setObjectName("three_d_label")
        self.gridLayout.addWidget(self.three_d_label, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_combo_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tr_combo_b.setObjectName("tr_combo_b")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.gridLayout.addWidget(self.tr_combo_b, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_combo_a = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tr_combo_a.setObjectName("tr_combo_a")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.gridLayout.addWidget(self.tr_combo_a, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_combo_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.bl_combo_b.setObjectName("bl_combo_b")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.gridLayout.addWidget(self.bl_combo_b, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_combo_a = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tl_combo_a.setObjectName("tl_combo_a")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.gridLayout.addWidget(self.tl_combo_a, 0, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.cancel_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_9.addWidget(self.cancel_button)
        self.apply_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_9.addWidget(self.apply_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        PropertiesWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PropertiesWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 363, 25))
        self.menubar.setObjectName("menubar")
        PropertiesWindow.setMenuBar(self.menubar)

        self.retranslateUi(PropertiesWindow)
        self.tl_combo_b.setCurrentIndex(1)
        self.bl_combo_a.setCurrentIndex(1)
        self.tr_combo_b.setCurrentIndex(3)
        self.bl_combo_b.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(PropertiesWindow)

    def retranslateUi(self, PropertiesWindow):
        _translate = QtCore.QCoreApplication.translate
        PropertiesWindow.setWindowTitle(_translate("PropertiesWindow", "PropertiesWindow"))
        self.dataset_label.setText(_translate("PropertiesWindow", "DATASET #XXX"))
        self.tl_enabled.setText(_translate("PropertiesWindow", "Enabled"))
        self.tr_enabled.setText(_translate("PropertiesWindow", "Enabled"))
        self.tl_label.setText(_translate("PropertiesWindow", "Top Left"))
        self.three_d_enabled.setText(_translate("PropertiesWindow", "Enabled"))
        self.bl_enabled.setText(_translate("PropertiesWindow", "Enabled"))
        self.tl_combo_b.setItemText(0, _translate("PropertiesWindow", "X"))
        self.tl_combo_b.setItemText(1, _translate("PropertiesWindow", "Y"))
        self.tl_combo_b.setItemText(2, _translate("PropertiesWindow", "Z"))
        self.tl_combo_b.setItemText(3, _translate("PropertiesWindow", "PX"))
        self.tl_combo_b.setItemText(4, _translate("PropertiesWindow", "PY"))
        self.tl_combo_b.setItemText(5, _translate("PropertiesWindow", "PZ"))
        self.bl_combo_a.setItemText(0, _translate("PropertiesWindow", "X"))
        self.bl_combo_a.setItemText(1, _translate("PropertiesWindow", "Y"))
        self.bl_combo_a.setItemText(2, _translate("PropertiesWindow", "Z"))
        self.bl_combo_a.setItemText(3, _translate("PropertiesWindow", "PX"))
        self.bl_combo_a.setItemText(4, _translate("PropertiesWindow", "PY"))
        self.bl_combo_a.setItemText(5, _translate("PropertiesWindow", "PZ"))
        self.tr_label.setText(_translate("PropertiesWindow", "Top Right"))
        self.bl_label.setText(_translate("PropertiesWindow", "Bottom Left"))
        self.three_d_label.setText(_translate("PropertiesWindow", "3D Plot"))
        self.tr_combo_b.setItemText(0, _translate("PropertiesWindow", "X"))
        self.tr_combo_b.setItemText(1, _translate("PropertiesWindow", "Y"))
        self.tr_combo_b.setItemText(2, _translate("PropertiesWindow", "Z"))
        self.tr_combo_b.setItemText(3, _translate("PropertiesWindow", "PX"))
        self.tr_combo_b.setItemText(4, _translate("PropertiesWindow", "PY"))
        self.tr_combo_b.setItemText(5, _translate("PropertiesWindow", "PZ"))
        self.tr_combo_a.setItemText(0, _translate("PropertiesWindow", "X"))
        self.tr_combo_a.setItemText(1, _translate("PropertiesWindow", "Y"))
        self.tr_combo_a.setItemText(2, _translate("PropertiesWindow", "Z"))
        self.tr_combo_a.setItemText(3, _translate("PropertiesWindow", "PX"))
        self.tr_combo_a.setItemText(4, _translate("PropertiesWindow", "PY"))
        self.tr_combo_a.setItemText(5, _translate("PropertiesWindow", "PZ"))
        self.bl_combo_b.setItemText(0, _translate("PropertiesWindow", "X"))
        self.bl_combo_b.setItemText(1, _translate("PropertiesWindow", "Y"))
        self.bl_combo_b.setItemText(2, _translate("PropertiesWindow", "Z"))
        self.bl_combo_b.setItemText(3, _translate("PropertiesWindow", "PX"))
        self.bl_combo_b.setItemText(4, _translate("PropertiesWindow", "PY"))
        self.bl_combo_b.setItemText(5, _translate("PropertiesWindow", "PZ"))
        self.tl_combo_a.setItemText(0, _translate("PropertiesWindow", "X"))
        self.tl_combo_a.setItemText(1, _translate("PropertiesWindow", "Y"))
        self.tl_combo_a.setItemText(2, _translate("PropertiesWindow", "Z"))
        self.tl_combo_a.setItemText(3, _translate("PropertiesWindow", "PX"))
        self.tl_combo_a.setItemText(4, _translate("PropertiesWindow", "PY"))
        self.tl_combo_a.setItemText(5, _translate("PropertiesWindow", "PZ"))
        self.cancel_button.setText(_translate("PropertiesWindow", "Cancel"))
        self.apply_button.setText(_translate("PropertiesWindow", "Apply"))

