# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'beamchargui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BeamChar(object):
    def setupUi(self, BeamChar):
        BeamChar.setObjectName("BeamChar")
        BeamChar.resize(421, 303)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BeamChar.sizePolicy().hasHeightForWidth())
        BeamChar.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(BeamChar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 3, 401, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.centroid = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.centroid.setText("")
        self.centroid.setObjectName("centroid")
        self.gridLayout.addWidget(self.centroid, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.rms = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.rms.setText("")
        self.rms.setObjectName("rms")
        self.gridLayout.addWidget(self.rms, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.halo = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.halo.setText("")
        self.halo.setObjectName("halo")
        self.gridLayout.addWidget(self.halo, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.turnsep = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.turnsep.setText("")
        self.turnsep.setObjectName("turnsep")
        self.gridLayout.addWidget(self.turnsep, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        BeamChar.setCentralWidget(self.centralwidget)

        self.retranslateUi(BeamChar)
        QtCore.QMetaObject.connectSlotsByName(BeamChar)

    def retranslateUi(self, BeamChar):
        _translate = QtCore.QCoreApplication.translate
        BeamChar.setWindowTitle(_translate("BeamChar", "Choosing Plots"))
        self.label.setText(_translate("BeamChar", "<html><head/><body><p>Please select the beam characteristic(s) you would like to plot.</p></body></html>"))
        self.label_3.setText(_translate("BeamChar", "Halo Parameter"))
        self.label_2.setText(_translate("BeamChar", "RMS Beam Size"))
        self.label_4.setText(_translate("BeamChar", "Centroid Position"))
        self.label_5.setText(_translate("BeamChar", "Turn Separation"))

