# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/default_plot_settings.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DefaultPlotSettingsWindow(object):
    def setupUi(self, DefaultPlotSettingsWindow):
        DefaultPlotSettingsWindow.setObjectName("DefaultPlotSettingsWindow")
        DefaultPlotSettingsWindow.resize(377, 251)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DefaultPlotSettingsWindow.sizePolicy().hasHeightForWidth())
        DefaultPlotSettingsWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(DefaultPlotSettingsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 374, 247))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_label.sizePolicy().hasHeightForWidth())
        self.main_label.setSizePolicy(sizePolicy)
        self.main_label.setObjectName("main_label")
        self.verticalLayout_3.addWidget(self.main_label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.bl_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.bl_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bl_enabled.setCheckable(True)
        self.bl_enabled.setChecked(True)
        self.bl_enabled.setObjectName("bl_enabled")
        self.gridLayout.addWidget(self.bl_enabled, 3, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_combo_a = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tl_combo_a.setObjectName("tl_combo_a")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.tl_combo_a.addItem("")
        self.gridLayout.addWidget(self.tl_combo_a, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_combo_a = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.bl_combo_a.setObjectName("bl_combo_a")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.bl_combo_a.addItem("")
        self.gridLayout.addWidget(self.bl_combo_a, 3, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tl_enabled.setEnabled(True)
        self.tl_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tl_enabled.setCheckable(True)
        self.tl_enabled.setChecked(True)
        self.tl_enabled.setObjectName("tl_enabled")
        self.gridLayout.addWidget(self.tl_enabled, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tl_label.setObjectName("tl_label")
        self.gridLayout.addWidget(self.tl_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tr_label.setObjectName("tr_label")
        self.gridLayout.addWidget(self.tr_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.step_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.step_label.setObjectName("step_label")
        self.gridLayout.addWidget(self.step_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_combo_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tr_combo_b.setObjectName("tr_combo_b")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.tr_combo_b.addItem("")
        self.gridLayout.addWidget(self.tr_combo_b, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_combo_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.bl_combo_b.setObjectName("bl_combo_b")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.bl_combo_b.addItem("")
        self.gridLayout.addWidget(self.bl_combo_b, 3, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.three_d_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.three_d_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.three_d_enabled.setCheckable(True)
        self.three_d_enabled.setObjectName("three_d_enabled")
        self.gridLayout.addWidget(self.three_d_enabled, 4, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_combo_a = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tr_combo_a.setObjectName("tr_combo_a")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.tr_combo_a.addItem("")
        self.gridLayout.addWidget(self.tr_combo_a, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tl_combo_b = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.tl_combo_b.setObjectName("tl_combo_b")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.tl_combo_b.addItem("")
        self.gridLayout.addWidget(self.tl_combo_b, 1, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bl_label.setObjectName("bl_label")
        self.gridLayout.addWidget(self.bl_label, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.step_input = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.step_input.setMinimum(0)
        self.step_input.setMaximum(999999999)
        self.step_input.setObjectName("step_input")
        self.gridLayout.addWidget(self.step_input, 0, 1, 1, 1)
        self.three_d_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.three_d_label.setObjectName("three_d_label")
        self.gridLayout.addWidget(self.three_d_label, 4, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.tr_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.tr_enabled.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tr_enabled.setCheckable(True)
        self.tr_enabled.setChecked(True)
        self.tr_enabled.setObjectName("tr_enabled")
        self.gridLayout.addWidget(self.tr_enabled, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.redraw_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.redraw_label.setObjectName("redraw_label")
        self.gridLayout.addWidget(self.redraw_label, 5, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.redraw_enabled = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.redraw_enabled.setChecked(True)
        self.redraw_enabled.setObjectName("redraw_enabled")
        self.gridLayout.addWidget(self.redraw_enabled, 5, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.redraw_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.redraw_button.setObjectName("redraw_button")
        self.horizontalLayout_9.addWidget(self.redraw_button)
        spacerItem2 = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.cancel_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_9.addWidget(self.cancel_button)
        self.apply_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.apply_button.setDefault(True)
        self.apply_button.setObjectName("apply_button")
        self.horizontalLayout_9.addWidget(self.apply_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        DefaultPlotSettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DefaultPlotSettingsWindow)
        self.bl_combo_a.setCurrentIndex(1)
        self.tr_combo_b.setCurrentIndex(3)
        self.bl_combo_b.setCurrentIndex(4)
        self.tl_combo_b.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DefaultPlotSettingsWindow)

    def retranslateUi(self, DefaultPlotSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        DefaultPlotSettingsWindow.setWindowTitle(_translate("DefaultPlotSettingsWindow", "Properties"))
        self.main_label.setText(_translate("DefaultPlotSettingsWindow", "DEFAULT PLOT SETTINGS"))
        self.bl_enabled.setText(_translate("DefaultPlotSettingsWindow", "Enabled"))
        self.tl_combo_a.setItemText(0, _translate("DefaultPlotSettingsWindow", "X"))
        self.tl_combo_a.setItemText(1, _translate("DefaultPlotSettingsWindow", "Y"))
        self.tl_combo_a.setItemText(2, _translate("DefaultPlotSettingsWindow", "Z"))
        self.tl_combo_a.setItemText(3, _translate("DefaultPlotSettingsWindow", "PX"))
        self.tl_combo_a.setItemText(4, _translate("DefaultPlotSettingsWindow", "PY"))
        self.tl_combo_a.setItemText(5, _translate("DefaultPlotSettingsWindow", "PZ"))
        self.bl_combo_a.setItemText(0, _translate("DefaultPlotSettingsWindow", "X"))
        self.bl_combo_a.setItemText(1, _translate("DefaultPlotSettingsWindow", "Y"))
        self.bl_combo_a.setItemText(2, _translate("DefaultPlotSettingsWindow", "Z"))
        self.bl_combo_a.setItemText(3, _translate("DefaultPlotSettingsWindow", "PX"))
        self.bl_combo_a.setItemText(4, _translate("DefaultPlotSettingsWindow", "PY"))
        self.bl_combo_a.setItemText(5, _translate("DefaultPlotSettingsWindow", "PZ"))
        self.tl_enabled.setText(_translate("DefaultPlotSettingsWindow", "Enabled"))
        self.tl_label.setText(_translate("DefaultPlotSettingsWindow", "Top Left:"))
        self.tr_label.setText(_translate("DefaultPlotSettingsWindow", "Top Right:"))
        self.step_label.setText(_translate("DefaultPlotSettingsWindow", "Step #:"))
        self.tr_combo_b.setItemText(0, _translate("DefaultPlotSettingsWindow", "X"))
        self.tr_combo_b.setItemText(1, _translate("DefaultPlotSettingsWindow", "Y"))
        self.tr_combo_b.setItemText(2, _translate("DefaultPlotSettingsWindow", "Z"))
        self.tr_combo_b.setItemText(3, _translate("DefaultPlotSettingsWindow", "PX"))
        self.tr_combo_b.setItemText(4, _translate("DefaultPlotSettingsWindow", "PY"))
        self.tr_combo_b.setItemText(5, _translate("DefaultPlotSettingsWindow", "PZ"))
        self.bl_combo_b.setItemText(0, _translate("DefaultPlotSettingsWindow", "X"))
        self.bl_combo_b.setItemText(1, _translate("DefaultPlotSettingsWindow", "Y"))
        self.bl_combo_b.setItemText(2, _translate("DefaultPlotSettingsWindow", "Z"))
        self.bl_combo_b.setItemText(3, _translate("DefaultPlotSettingsWindow", "PX"))
        self.bl_combo_b.setItemText(4, _translate("DefaultPlotSettingsWindow", "PY"))
        self.bl_combo_b.setItemText(5, _translate("DefaultPlotSettingsWindow", "PZ"))
        self.three_d_enabled.setText(_translate("DefaultPlotSettingsWindow", "Enabled"))
        self.tr_combo_a.setItemText(0, _translate("DefaultPlotSettingsWindow", "X"))
        self.tr_combo_a.setItemText(1, _translate("DefaultPlotSettingsWindow", "Y"))
        self.tr_combo_a.setItemText(2, _translate("DefaultPlotSettingsWindow", "Z"))
        self.tr_combo_a.setItemText(3, _translate("DefaultPlotSettingsWindow", "PX"))
        self.tr_combo_a.setItemText(4, _translate("DefaultPlotSettingsWindow", "PY"))
        self.tr_combo_a.setItemText(5, _translate("DefaultPlotSettingsWindow", "PZ"))
        self.tl_combo_b.setItemText(0, _translate("DefaultPlotSettingsWindow", "X"))
        self.tl_combo_b.setItemText(1, _translate("DefaultPlotSettingsWindow", "Y"))
        self.tl_combo_b.setItemText(2, _translate("DefaultPlotSettingsWindow", "Z"))
        self.tl_combo_b.setItemText(3, _translate("DefaultPlotSettingsWindow", "PX"))
        self.tl_combo_b.setItemText(4, _translate("DefaultPlotSettingsWindow", "PY"))
        self.tl_combo_b.setItemText(5, _translate("DefaultPlotSettingsWindow", "PZ"))
        self.bl_label.setText(_translate("DefaultPlotSettingsWindow", "Bottom Left:"))
        self.three_d_label.setText(_translate("DefaultPlotSettingsWindow", "3D Plot:"))
        self.tr_enabled.setText(_translate("DefaultPlotSettingsWindow", "Enabled"))
        self.redraw_label.setText(_translate("DefaultPlotSettingsWindow", "Redraw On Selection: "))
        self.redraw_enabled.setText(_translate("DefaultPlotSettingsWindow", "Enabled"))
        self.redraw_button.setText(_translate("DefaultPlotSettingsWindow", "Redraw"))
        self.cancel_button.setText(_translate("DefaultPlotSettingsWindow", "Cancel"))
        self.apply_button.setText(_translate("DefaultPlotSettingsWindow", "Apply"))

