# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Generate_Main(object):
    def setupUi(self, Generate_Main):
        Generate_Main.setObjectName("Generate_Main")
        Generate_Main.resize(419, 252)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Generate_Main.sizePolicy().hasHeightForWidth())
        Generate_Main.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Generate_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 401, 232))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tr_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tr_label.setObjectName("tr_label")
        self.gridLayout.addWidget(self.tr_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(164, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.tl_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tl_label.setObjectName("tl_label")
        self.gridLayout.addWidget(self.tl_label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.bl_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.bl_label.setObjectName("bl_label")
        self.gridLayout.addWidget(self.bl_label, 6, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setMinimumSize(QtCore.QSize(164, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.energy = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.energy.setMaximumSize(QtCore.QSize(164, 16777215))
        self.energy.setObjectName("energy")
        self.gridLayout.addWidget(self.energy, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)
        Generate_Main.setCentralWidget(self.centralwidget)

        self.retranslateUi(Generate_Main)
        QtCore.QMetaObject.connectSlotsByName(Generate_Main)

    def retranslateUi(self, Generate_Main):
        _translate = QtCore.QCoreApplication.translate
        Generate_Main.setWindowTitle(_translate("Generate_Main", "Generate Distribution"))
        self.tr_label.setText(_translate("Generate_Main", "Species:"))
        self.tl_label.setText(_translate("Generate_Main", "Number of Particles:"))
        self.bl_label.setText(_translate("Generate_Main", "Input Parameter Type:"))
        self.comboBox_2.setItemText(0, _translate("Generate_Main", "Envelope"))
        self.comboBox_2.setItemText(1, _translate("Generate_Main", "Twiss"))
        self.comboBox.setItemText(0, _translate("Generate_Main", "Proton"))
        self.comboBox.setItemText(1, _translate("Generate_Main", "Electron"))
        self.comboBox.setItemText(2, _translate("Generate_Main", "Dihydrogen cation"))
        self.comboBox.setItemText(3, _translate("Generate_Main", "Alpha particle"))
        self.label.setText(_translate("Generate_Main", "Energy (MeV):"))

